FROM mysql:8.0.44
ARG PPE_GIT_COMMIT=uncommitted
LABEL org.opencontainers.image.revision=$PPE_GIT_COMMIT
COPY containers/production/init-db.sh /docker-entrypoint-initdb.d/10-ppe.sh
COPY containers/production/db-admin.sh /opt/ppe/db-admin.sh
RUN chmod 0644 /docker-entrypoint-initdb.d/10-ppe.sh /opt/ppe/db-admin.sh
