package entity;

public enum ConsentSaveResult {
	RECORDED,
	ALREADY_RECORDED,
	NO_ACTIVE_DOCUMENT,
	DOCUMENT_CHANGED,
	RESPONSE_CHANGED,
	CONFIRMATION_REQUIRED,
	ACCOUNT_UNAVAILABLE,
	INVALID_DECISION
}
